services:
  iceberg-rest:
    image: tabulario/iceberg-rest:latest
    container_name: iceberg-rest
    ports:
      - "8181:8181"
    volumes:
      - ~/numbuzz-test-data/iceberg-rest:/home/iceberg/warehouse

  iceberg-init:
    image: curlimages/curl:latest
    depends_on:
      - iceberg-rest
    volumes:
      - ./init_iceberg_tables.sh:/init_iceberg_tables.sh:ro
    entrypoint: [ "sh", "/init_iceberg_tables.sh" ]

  buzzintake:
    build: .
    container_name: buzzintake
    ports:
      - "8080:8080"
    depends_on:
      - iceberg-init
    environment:
      - ICEBERG_REST_URI=http://iceberg-rest:8181/
      - ICEBERG_WAREHOUSE=/home/iceberg/warehouse
      - JAVA_OPTS=-Xmx2g -Xms1g
      - SERVER_PORT=8080
    volumes:
      - ~/numbuzz-test-data/buzzintake-stage_data:/home/iceberg/warehouse
      - ~/numbuzz-test-data/buzzintake-app-data:/app/data:ro 
volumes:
  iceberg-data:
    driver: local
  buzzintake-data:
    driver: local 